-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.28-0ubuntu0.16.04.2 - (Ubuntu)
-- Server OS:                    Linux
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for reestr
CREATE DATABASE IF NOT EXISTS `reestr` /*!40100 DEFAULT CHARACTER SET cp1251 */;
USE `reestr`;

-- Dumping structure for table reestr.countries_and_codes
CREATE TABLE IF NOT EXISTS `countries_and_codes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name_lat` varchar(100) NOT NULL,
  `name_cyr` varchar(100) DEFAULT NULL,
  `short_code` varchar(10) DEFAULT NULL,
  `mobile_code` varchar(100) DEFAULT NULL,
  `flag_picture_name` text,
  `flag_path` text,
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=612 DEFAULT CHARSET=cp1251 COMMENT='страны и коды';

-- Dumping data for table reestr.countries_and_codes: ~200 rows (approximately)
/*!40000 ALTER TABLE `countries_and_codes` DISABLE KEYS */;
INSERT INTO `countries_and_codes` (`id`, `name_lat`, `name_cyr`, `short_code`, `mobile_code`, `flag_picture_name`, `flag_path`) VALUES
	(412, 'Afghanistan', 'Афганистан', 'AF / AFG', '93', 'afghanistan.png', '../assets/img/flags/afghanistan.png'),
	(413, 'Albania', 'Албания', 'AL / ALB', '355', 'albania.png', '../assets/img/flags/albania.png'),
	(414, 'Algeria', 'Алжир', 'DZ / DZA', '213', 'algeria.png', '../assets/img/flags/algeria.png'),
	(415, 'Andorra', 'Андорра', 'AD / AND', '376', 'andorra.png', '../assets/img/flags/andorra.png'),
	(416, 'Angola', 'Ангола', 'AO / AGO', '244', 'angola.png', '../assets/img/flags/angola.png'),
	(417, 'Antigua and Barbuda', 'Антигуа и Барбуда', 'AG / ATG', '1-268', 'antigua_and_barbuda.png', '../assets/img/flags/antigua_and_barbuda.png'),
	(418, 'Argentina', 'Аргентина', 'AR / ARG', '54', 'argentina.png', '../assets/img/flags/argentina.png'),
	(419, 'Armenia', 'Армения', 'AM / ARM', '374', 'armenia.png', '../assets/img/flags/armenia.png'),
	(420, 'Australia', 'Австралия', 'AU / AUS', '61', 'australia.png', '../assets/img/flags/australia.png'),
	(421, 'Austria', 'Австрия', 'AT / AUT', '43', 'austria.png', '../assets/img/flags/austria.png'),
	(422, 'Azerbaijan', 'Азербайджан', 'AZ / AZE', '994', 'azerbaijan.png', '../assets/img/flags/azerbaijan.png'),
	(423, 'The Bahamas', 'Багамские острова', 'BS / BHS', '1-242', 'the_bahamas.png', '../assets/img/flags/the_bahamas.png'),
	(424, 'Bahrain', 'Бахрейн', 'BH / BHR', '973', 'bahrain.png', '../assets/img/flags/bahrain.png'),
	(425, 'Bangladesh', 'Бангладеш', 'BD / BGD', '880', 'bangladesh.png', '../assets/img/flags/bangladesh.png'),
	(426, 'Barbados', 'Барбадос', 'BB / BRB', '1-246', 'barbados.png', '../assets/img/flags/barbados.png'),
	(427, 'Belarus', 'Беларусь', 'BY / BLR', '375', 'belarus.png', '../assets/img/flags/belarus.png'),
	(428, 'Belgium', 'Бельгия', 'BE / BEL', '32', 'belgium.png', '../assets/img/flags/belgium.png'),
	(429, 'Belize', 'Белиз', 'BZ / BLZ', '501', 'belize.png', '../assets/img/flags/belize.png'),
	(430, 'Benin', 'Бенин', 'BJ / BEN', '229', 'benin.png', '../assets/img/flags/benin.png'),
	(431, 'Bhutan', 'Бутан', 'BT / BTN', '975', 'bhutan.png', '../assets/img/flags/bhutan.png'),
	(432, 'Bolivia', 'Боливия', 'BO / BOL', '591', 'bolivia.png', '../assets/img/flags/bolivia.png'),
	(433, 'Bosnia and Herzegovina', 'Босния и Герцеговина', 'BA / BIH', '387', 'bosnia_and_herzegovina.png', '../assets/img/flags/bosnia_and_herzegovina.png'),
	(434, 'Botswana', 'Ботсвана', 'BW / BWA', '267', 'botswana.png', '../assets/img/flags/botswana.png'),
	(435, 'Brazil', 'Бразилия', 'BR / BRA', '55', 'brazil.png', '../assets/img/flags/brazil.png'),
	(436, 'Brunei', 'Бруней', 'BN / BRN', '673', 'brunei.png', '../assets/img/flags/brunei.png'),
	(437, 'Bulgaria', 'Болгария', 'BG / BGR', '359', 'bulgaria.png', '../assets/img/flags/bulgaria.png'),
	(438, 'Burkina Faso', 'Буркина - Фасо', 'BF / BFA', '226', 'burkina_faso.png', '../assets/img/flags/burkina_faso.png'),
	(439, 'Burundi', 'Бурунди', 'BI / BDI', '257', 'burundi.png', '../assets/img/flags/burundi.png'),
	(440, 'Cambodia', 'Камбоджа', 'KH / KHM', '855', 'cambodia.png', '../assets/img/flags/cambodia.png'),
	(441, 'Cameroon', 'Камерун', 'CM / CMR', '237', 'cameroon.png', '../assets/img/flags/cameroon.png'),
	(442, 'Canada', 'Канада', 'CA / CAN', '1', 'canada.png', '../assets/img/flags/canada.png'),
	(443, 'Cape Verde', 'Кабо-Верде', 'CV / CPV', '238', 'cape_verde.png', '../assets/img/flags/cape_verde.png'),
	(444, 'The Central African Republic', 'Центральноафриканская Республика', 'CF / CAF', '236', 'the_central_african_republic.png', '../assets/img/flags/the_central_african_republic.png'),
	(445, 'Chad', 'Чад', 'TD / TCD', '235', 'chad.png', '../assets/img/flags/chad.png'),
	(446, 'Chile', 'Чили', 'CL / CHL', '56', 'chile.png', '../assets/img/flags/chile.png'),
	(447, 'Colombia', 'Колумбия', 'CO / COL', '57', 'colombia.png', '../assets/img/flags/colombia.png'),
	(448, 'The Comoros', 'Коморы', 'KM / COM', '269', 'the_comoros.png', '../assets/img/flags/the_comoros.png'),
	(449, 'Cook Islands', 'Острова Кука', 'CK / COK', '682', 'cook_islands.png', '../assets/img/flags/cook_islands.png'),
	(450, 'Costa Rica', 'Коста-Рика', 'CR / CRI', '506', 'costa_rica.png', '../assets/img/flags/costa_rica.png'),
	(451, 'Cote d\'Ivoire', 'Республика Кот-д’Ивуар', 'CI /CIV', '225', 'cote_d\'ivoire.png', '../assets/img/flags/cote_d\'ivoire.png'),
	(452, 'Croatia', 'Хорватия', 'HR / HRV', '385', 'croatia.png', '../assets/img/flags/croatia.png'),
	(453, 'Cuba', 'Куба', 'CU / CUB', '53', 'cuba.png', '../assets/img/flags/cuba.png'),
	(454, 'Cyprus', 'Кипр', 'CY / CYP', '357', 'cyprus.png', '../assets/img/flags/cyprus.png'),
	(455, 'The Czech Republic', 'Чехия', 'CZ / CZE', '420', 'the_czech_republic.png', '../assets/img/flags/the_czech_republic.png'),
	(456, 'The Democratic Republic of the Congo', 'Республика Конго', 'CD / COD', '243', 'the_democratic_republic_of_the_congo.png', '../assets/img/flags/the_democratic_republic_of_the_congo.png'),
	(457, 'Denmark', 'Дания', 'DK / DNK', '45', 'denmark.png', '../assets/img/flags/denmark.png'),
	(458, 'Djibouti', 'Джибути', 'DJ / DJI', '253', 'djibouti.png', '../assets/img/flags/djibouti.png'),
	(459, 'Dominica', 'Доминика', 'DM / DMA', '1-767', 'dominica.png', '../assets/img/flags/dominica.png'),
	(460, 'The Dominican Republic', 'Доминиканская республика', 'DO / DOM', '1-809, 1-829, 1-849', 'the_dominican_republic.png', '../assets/img/flags/the_dominican_republic.png'),
	(461, 'East Timor', 'Восточный Тимор', 'TL / TLS', '670', 'east_timor.png', '../assets/img/flags/east_timor.png'),
	(462, 'Ecuador', 'Эквадор', 'EC / ECU', '593', 'ecuador.png', '../assets/img/flags/ecuador.png'),
	(463, 'Egypt', 'Египет', 'EG / EGY', '20', 'egypt.png', '../assets/img/flags/egypt.png'),
	(464, 'El Salvador', 'Сальвадор', 'SV / SLV', '503', 'el_salvador.png', '../assets/img/flags/el_salvador.png'),
	(465, 'Equatorial Guinea', 'Экваториальная Гвинея', 'GQ / GNQ', '240', 'equatorial_guinea.png', '../assets/img/flags/equatorial_guinea.png'),
	(466, 'Eritrea', 'Эритрея', 'ER / ERI', '291', 'eritrea.png', '../assets/img/flags/eritrea.png'),
	(467, 'Estonia', 'Эстония', 'EE / EST', '372', 'estonia.png', '../assets/img/flags/estonia.png'),
	(468, 'Ethiopia', 'Эфиопия', 'ET / ETH', '251', 'ethiopia.png', '../assets/img/flags/ethiopia.png'),
	(469, 'Fiji', 'Фиджи', 'FJ / FJI', '679', 'fiji.png', '../assets/img/flags/fiji.png'),
	(470, 'Finland', 'Финляндия', 'FI / FIN', '358', 'finland.png', '../assets/img/flags/finland.png'),
	(471, 'France', 'Франция', 'FR / FRA', '33', 'france.png', '../assets/img/flags/france.png'),
	(472, 'Gabon', 'Габон', 'GA / GAB', '241', 'gabon.png', '../assets/img/flags/gabon.png'),
	(473, 'The Gambia', 'Гамбия', 'GM / GMB', '220', 'the_gambia.png', '../assets/img/flags/the_gambia.png'),
	(474, 'Georgia', 'Грузия', 'GE / GEO', '995', 'georgia.png', '../assets/img/flags/georgia.png'),
	(475, 'Germany', 'Германия', 'DE / DEU', '49', 'germany.png', '../assets/img/flags/germany.png'),
	(476, 'Ghana', 'Гана', 'GH / GHA', '233', 'ghana.png', '../assets/img/flags/ghana.png'),
	(477, 'Greece', 'Греция', 'GR / GRC', '30', 'greece.png', '../assets/img/flags/greece.png'),
	(478, 'Grenada', 'Гренада', 'GD / GRD', '1-473', 'grenada.png', '../assets/img/flags/grenada.png'),
	(479, 'Guatemala', 'Гватемала', 'GT / GTM', '502', 'guatemala.png', '../assets/img/flags/guatemala.png'),
	(480, 'Guinea', 'Гвинея', 'GN / GIN', '224', 'guinea.png', '../assets/img/flags/guinea.png'),
	(481, 'Guinea-Bissau', 'Гвинея-Бисау', 'GW / GNB', '245', 'guinea-bissau.png', '../assets/img/flags/guinea-bissau.png'),
	(482, 'Guyana', 'Гайана', 'GY / GUY', '592', 'guyana.png', '../assets/img/flags/guyana.png'),
	(483, 'Haiti', 'Гаити', 'HT / HTI', '509', 'haiti.png', '../assets/img/flags/haiti.png'),
	(484, 'Honduras', 'Гондурас', 'HN / HND', '504', 'honduras.png', '../assets/img/flags/honduras.png'),
	(485, 'Hungary', 'Венгрия', 'HU / HUN', '36', 'hungary.png', '../assets/img/flags/hungary.png'),
	(486, 'Iceland', 'Исландия', 'IS / ISL', '354', 'iceland.png', '../assets/img/flags/iceland.png'),
	(487, 'India', 'Индия', 'IN / IND', '91', 'india.png', '../assets/img/flags/india.png'),
	(488, 'Indonesia', 'Индонезия', 'ID / IDN', '62', 'indonesia.png', '../assets/img/flags/indonesia.png'),
	(489, 'Iran', 'Иран', 'IR / IRN', '98', 'iran.png', '../assets/img/flags/iran.png'),
	(490, 'Iraq', 'Ирак', 'IQ / IRQ', '964', 'iraq.png', '../assets/img/flags/iraq.png'),
	(491, 'Ireland', 'Ирландия', 'IE / IRL', '353', 'ireland.png', '../assets/img/flags/ireland.png'),
	(492, 'Israel', 'Израиль', 'IL / ISR', '972', 'israel.png', '../assets/img/flags/israel.png'),
	(493, 'Italy', 'Италия', 'IT / ITA', '39', 'italy.png', '../assets/img/flags/italy.png'),
	(494, 'Jamaica', 'Ямайка', 'JM / JAM', '1-876', 'jamaica.png', '../assets/img/flags/jamaica.png'),
	(495, 'Japan', 'Япония', 'JP / JPN', '81', 'japan.png', '../assets/img/flags/japan.png'),
	(496, 'Jordan', 'Иордания', 'JO / JOR', '962', 'jordan.png', '../assets/img/flags/jordan.png'),
	(497, 'Kazakhstan', 'Казахстан', 'KZ / KAZ', '7', 'kazakhstan.png', '../assets/img/flags/kazakhstan.png'),
	(498, 'Kenya', 'Кения', 'KE / KEN', '254', 'kenya.png', '../assets/img/flags/kenya.png'),
	(499, 'Kiribati', 'Кирибати', 'KI / KIR', '686', 'kiribati.png', '../assets/img/flags/kiribati.png'),
	(500, 'Kosovo', 'Косово', 'XK / XKX', '383', 'kosovo.png', '../assets/img/flags/kosovo.png'),
	(501, 'Kuwait', 'Кувейт', 'KW / KWT', '965', 'kuwait.png', '../assets/img/flags/kuwait.png'),
	(502, 'Kyrgyzstan', 'Кыргызстан', 'KG / KGZ', '996', 'kyrgyzstan.png', '../assets/img/flags/kyrgyzstan.png'),
	(503, 'Laos', 'Лаос', 'LA / LAO', '856', 'laos.png', '../assets/img/flags/laos.png'),
	(504, 'Latvia', 'Латвия', 'LV / LVA', '371', 'latvia.png', '../assets/img/flags/latvia.png'),
	(505, 'Lebanon', 'Ливан', 'LB / LBN', '961', 'lebanon.png', '../assets/img/flags/lebanon.png'),
	(506, 'Lesotho', 'Лесото', 'LS / LSO', '266', 'lesotho.png', '../assets/img/flags/lesotho.png'),
	(507, 'Liberia', 'Либерия', 'LR / LBR', '231', 'liberia.png', '../assets/img/flags/liberia.png'),
	(508, 'Libya', 'Ливия', 'LY / LBY', '218', 'libya.png', '../assets/img/flags/libya.png'),
	(509, 'Liechtenstein', 'Лихтенштейн', 'LI / LIE', '423', 'liechtenstein.png', '../assets/img/flags/liechtenstein.png'),
	(510, 'Lithuania', 'Литва', 'LT / LTU', '370', 'lithuania.png', '../assets/img/flags/lithuania.png'),
	(511, 'Luxembourg', 'Люксембург', 'LU / LUX', '352', 'luxembourg.png', '../assets/img/flags/luxembourg.png'),
	(512, 'Macedonia', 'Македония', 'MK / MKD', '389', 'macedonia.png', '../assets/img/flags/macedonia.png'),
	(513, 'Madagascar', 'Мадагаскар', 'MG / MDG', '261', 'madagascar.png', '../assets/img/flags/madagascar.png'),
	(514, 'Malawi', 'Малави', 'MW / MWI', '265', 'malawi.png', '../assets/img/flags/malawi.png'),
	(515, 'Malaysia', 'Малайзия', 'MY / MYS', '60', 'malaysia.png', '../assets/img/flags/malaysia.png'),
	(516, 'Maldives', 'Мальдивы', 'MV / MDV', '960', 'maldives.png', '../assets/img/flags/maldives.png'),
	(517, 'Mali', 'Мали', 'ML / MLI', '223', 'mali.png', '../assets/img/flags/mali.png'),
	(518, 'Malta', 'Мальта', 'MT / MLT', '356', 'malta.png', '../assets/img/flags/malta.png'),
	(519, 'The Marshall Islands', 'Маршаловы острова', 'MH / MHL', '692', 'the_marshall_islands.png', '../assets/img/flags/the_marshall_islands.png'),
	(520, 'Mauritania', 'Мавритания', 'MR / MRT', '222', 'mauritania.png', '../assets/img/flags/mauritania.png'),
	(521, 'Mauritius', 'остров Маврикий', 'MU / MUS', '230', 'mauritius.png', '../assets/img/flags/mauritius.png'),
	(522, 'Mexico', 'Мексика', 'MX / MEX', '52', 'mexico.png', '../assets/img/flags/mexico.png'),
	(523, 'Micronesia', 'Микронезия', 'FM / FSM', '691', 'micronesia.png', '../assets/img/flags/micronesia.png'),
	(524, 'Moldova', 'Молдова', 'MD / MDA', '373', 'moldova.png', '../assets/img/flags/moldova.png'),
	(525, 'Monaco', 'Монако', 'MC / MCO', '377', 'monaco.png', '../assets/img/flags/monaco.png'),
	(526, 'Mongolia', 'Монголия', 'MN / MNG', '976', 'mongolia.png', '../assets/img/flags/mongolia.png'),
	(527, 'Montenegro', 'Монтенегро', 'ME / MNE', '382', 'montenegro.png', '../assets/img/flags/montenegro.png'),
	(528, 'Morocco', 'Морокко', 'MA / MAR', '212', 'morocco.png', '../assets/img/flags/morocco.png'),
	(529, 'Mozambique', 'Мозамбик', 'MZ / MOZ', '258', 'mozambique.png', '../assets/img/flags/mozambique.png'),
	(530, 'Myanmar', 'Мьянма', 'MM / MMR', '95', 'myanmar.png', '../assets/img/flags/myanmar.png'),
	(531, 'Namibia', 'Намибия', 'NA / NAM', '264', 'namibia.png', '../assets/img/flags/namibia.png'),
	(532, 'Nauru', 'Наура', 'NR / NRU', '674', 'nauru.png', '../assets/img/flags/nauru.png'),
	(533, 'Nepal', 'Непал', 'NP / NPL', '977', 'nepal.png', '../assets/img/flags/nepal.png'),
	(534, 'The Netherlands', 'Нидерланды', 'NL / NLD', '31', 'the_netherlands.png', '../assets/img/flags/the_netherlands.png'),
	(535, 'New Zealand', 'Новая Зеландия', 'NZ / NZL', '64', 'new_zealand.png', '../assets/img/flags/new_zealand.png'),
	(536, 'Nicaragua', 'Никарагуа', 'NI / NIC', '505', 'nicaragua.png', '../assets/img/flags/nicaragua.png'),
	(537, 'Niger', 'Нигер', 'NE / NER', '227', 'niger.png', '../assets/img/flags/niger.png'),
	(538, 'Nigeria', 'Нигерия', 'NG / NGA', '234', 'nigeria.png', '../assets/img/flags/nigeria.png'),
	(539, 'Niue', 'Ниуэ', 'NU / NIU', '683', 'niue.png', '../assets/img/flags/niue.png'),
	(540, 'North Korea', 'Северная Корея', 'KP / PRK', '850', 'north_korea.png', '../assets/img/flags/north_korea.png'),
	(541, 'Norway', 'Норвегия', 'NO / NOR', '47', 'norway.png', '../assets/img/flags/norway.png'),
	(542, 'Oman', 'Оман', 'OM / OMN', '968', 'oman.png', '../assets/img/flags/oman.png'),
	(543, 'Pakistan', 'Пакистан', 'PK / PAK', '92', 'pakistan.png', '../assets/img/flags/pakistan.png'),
	(544, 'Palau', 'Палау', 'PW / PLW', '680', 'palau.png', '../assets/img/flags/palau.png'),
	(545, 'Panama', 'Панама', 'PA / PAN', '507', 'panama.png', '../assets/img/flags/panama.png'),
	(546, 'Papua New Guinea', 'Папуа-Новая Гвинея', 'PG / PNG', '675', 'papua_new_guinea.png', '../assets/img/flags/papua_new_guinea.png'),
	(547, 'Paraguay', 'Парагвай', 'PY / PRY', '595', 'paraguay.png', '../assets/img/flags/paraguay.png'),
	(548, 'The People\'s Republic of China', 'Китайская Народная Республика', 'CN / CHN', '86', 'the_people\'s_republic_of_china.png', '../assets/img/flags/the_people\'s_republic_of_china.png'),
	(549, 'Peru', 'Перу', 'PE / PER', '51', 'peru.png', '../assets/img/flags/peru.png'),
	(550, 'The Philippines', 'Филиппины', 'PH / PHL', '63', 'the_philippines.png', '../assets/img/flags/the_philippines.png'),
	(551, 'Poland', 'Польша', 'PL / POL', '48', 'poland.png', '../assets/img/flags/poland.png'),
	(552, 'Portugal', 'Португалия', 'PT / PRT', '351', 'portugal.png', '../assets/img/flags/portugal.png'),
	(553, 'Qatar', 'Катар', 'QA / QAT', '974', 'qatar.png', '../assets/img/flags/qatar.png'),
	(554, 'The Republic of China', 'Тайвань', 'TW / TWN', '886', 'the_republic_of_china.png', '../assets/img/flags/the_republic_of_china.png'),
	(555, 'The Republic of the Congo', 'Республика Конго', 'CG / COG', '242', 'the_republic_of_the_congo.png', '../assets/img/flags/the_republic_of_the_congo.png'),
	(556, 'Romania', 'Румыния', 'RO / ROU', '40', 'romania.png', '../assets/img/flags/romania.png'),
	(557, 'Russia', 'Россия', 'RU / RUS', '7', 'russia.png', '../assets/img/flags/russia.png'),
	(558, 'Rwanda', 'Руанда', 'RW / RWA', '250', 'rwanda.png', '../assets/img/flags/rwanda.png'),
	(559, 'Saint Kitts and Nevis', 'Сент-Китс', 'KN / KNA', '1-869', 'saint_kitts_and_nevis.png', '../assets/img/flags/saint_kitts_and_nevis.png'),
	(560, 'Saint Lucia', 'Сент-Лусия', 'LC / LCA', '1-758', 'saint_lucia.png', '../assets/img/flags/saint_lucia.png'),
	(561, 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины', 'VC / VCT', '1-784', 'saint_vincent_and_the_grenadines.png', '../assets/img/flags/saint_vincent_and_the_grenadines.png'),
	(562, 'Samoa', 'Самоа', 'WS / WSM', '685', 'samoa.png', '../assets/img/flags/samoa.png'),
	(563, 'San Marino', 'Сан-Марино', 'SM / SMR', '378', 'san_marino.png', '../assets/img/flags/san_marino.png'),
	(564, 'Sao Tome and Principe', 'Сан-Томе и Принсипи', 'ST / STP', '239', 'sao_tome_and_principe.png', '../assets/img/flags/sao_tome_and_principe.png'),
	(565, 'Saudi Arabia', 'Саудовская Аравия', 'SA / SAU', '966', 'saudi_arabia.png', '../assets/img/flags/saudi_arabia.png'),
	(566, 'Senegal', 'Сенегал', 'SN / SEN', '221', 'senegal.png', '../assets/img/flags/senegal.png'),
	(567, 'Serbia', 'Сербия', 'RS / SRB', '381', 'serbia.png', '../assets/img/flags/serbia.png'),
	(568, 'The Seychelles', 'Сейшелы', 'SC / SYC', '248', 'the_seychelles.png', '../assets/img/flags/the_seychelles.png'),
	(569, 'Sierra Leone', 'Сьерра-Леоне', 'SL / SLE', '232', 'sierra_leone.png', '../assets/img/flags/sierra_leone.png'),
	(570, 'Singapore', 'Сингапур', 'SG / SGP', '65', 'singapore.png', '../assets/img/flags/singapore.png'),
	(571, 'Slovakia', 'Словакия', 'SK / SVK', '421', 'slovakia.png', '../assets/img/flags/slovakia.png'),
	(572, 'Slovenia', 'Словения', 'SI / SVN', '386', 'slovenia.png', '../assets/img/flags/slovenia.png'),
	(573, 'The Solomon Islands', 'Соломоновы острова', 'SB / SLB', '677', 'the_solomon_islands.png', '../assets/img/flags/the_solomon_islands.png'),
	(574, 'Somalia', 'Сомали', 'SO / SOM', '252', 'somalia.png', '../assets/img/flags/somalia.png'),
	(575, 'South Africa', 'Южная Африка', 'ZA / ZAF', '27', 'south_africa.png', '../assets/img/flags/south_africa.png'),
	(576, 'South Korea', 'Южная Корея', 'KR / KOR', '82', 'south_korea.png', '../assets/img/flags/south_korea.png'),
	(577, 'South Sudan', 'Южный Судан', 'SS / SSD', '211', 'south_sudan.png', '../assets/img/flags/south_sudan.png'),
	(578, 'Spain', 'Испания', 'ES / ESP', '34', 'spain.png', '../assets/img/flags/spain.png'),
	(579, 'Sri Lanka', 'Шри-Ланка', 'LK / LKA', '94', 'sri_lanka.png', '../assets/img/flags/sri_lanka.png'),
	(580, 'Palestine', 'Палестина', 'PS / PSE', '970', 'palestine.png', '../assets/img/flags/palestine.png'),
	(581, 'Sudan', 'Судан', 'SD / SDN', '249', 'sudan.png', '../assets/img/flags/sudan.png'),
	(582, 'Suriname', 'Суринам', 'SR / SUR', '597', 'suriname.png', '../assets/img/flags/suriname.png'),
	(583, 'Swaziland', 'Эсватини', 'SZ / SWZ', '268', 'swaziland.png', '../assets/img/flags/swaziland.png'),
	(584, 'Sweden', 'Швеция', 'SE / SWE', '46', 'sweden.png', '../assets/img/flags/sweden.png'),
	(585, 'Switzerland', 'Швейцария', 'CH / CHE', '41', 'switzerland.png', '../assets/img/flags/switzerland.png'),
	(586, 'Syria', 'Сирия', 'SY / SYR', '963', 'syria.png', '../assets/img/flags/syria.png'),
	(587, 'Tajikistan', 'Таджикистан', 'TJ / TJK', '992', 'tajikistan.png', '../assets/img/flags/tajikistan.png'),
	(588, 'Tanzania', 'Танзания', 'TZ / TZA', '255', 'tanzania.png', '../assets/img/flags/tanzania.png'),
	(589, 'Thailand', 'Тайланд', 'TH / THA', '66', 'thailand.png', '../assets/img/flags/thailand.png'),
	(590, 'Togo', 'Того', 'TG / TGO', '228', 'togo.png', '../assets/img/flags/togo.png'),
	(591, 'Tonga', 'Тонга', 'TO / TON', '676', 'tonga.png', '../assets/img/flags/tonga.png'),
	(592, 'Trinidad and Tobago', 'Тринидад и Тобаго', 'TT / TTO', '1-868', 'trinidad_and_tobago.png', '../assets/img/flags/trinidad_and_tobago.png'),
	(593, 'Tunisia', 'Тунис', 'TN / TUN', '216', 'tunisia.png', '../assets/img/flags/tunisia.png'),
	(594, 'Turkey', 'Турция', 'TR / TUR', '90', 'turkey.png', '../assets/img/flags/turkey.png'),
	(595, 'Turkmenistan', 'Туркменистан', 'TM / TKM', '993', 'turkmenistan.png', '../assets/img/flags/turkmenistan.png'),
	(596, 'Tuvalu', 'Тувалу', 'TV / TUV', '688', 'tuvalu.png', '../assets/img/flags/tuvalu.png'),
	(597, 'Uganda', 'Уганда', 'UG / UGA', '256', 'uganda.png', '../assets/img/flags/uganda.png'),
	(598, 'Ukraine', 'Украина', 'UA / UKR', '380', 'ukraine.png', '../assets/img/flags/ukraine.png'),
	(599, 'The United Arab Emirates', 'ОАЭ', 'AE / ARE', '971', 'the_united_arab_emirates.png', '../assets/img/flags/the_united_arab_emirates.png'),
	(600, 'The United Kingdom', 'Великобритания', 'GB / GBR', '44', 'the_united_kingdom.png', '../assets/img/flags/the_united_kingdom.png'),
	(601, 'The United States', 'США', 'US / USA', '1', 'the_united_states.png', '../assets/img/flags/the_united_states.png'),
	(602, 'Uruguay', 'Уругвай', 'UY / URY', '598', 'uruguay.png', '../assets/img/flags/uruguay.png'),
	(603, 'Uzbekistan', 'Узбекистан', 'UZ / UZB', '998', 'uzbekistan.png', '../assets/img/flags/uzbekistan.png'),
	(604, 'Vanuatu', 'Вануату', 'VU / VUT', '678', 'vanuatu.png', '../assets/img/flags/vanuatu.png'),
	(605, 'The Vatican City', 'Ватикан', 'VA / VAT', '379', 'the_vatican_city.png', '../assets/img/flags/the_vatican_city.png'),
	(606, 'Venezuela', 'Венесуэла', 'VE / VEN', '58', 'venezuela.png', '../assets/img/flags/venezuela.png'),
	(607, 'Vietnam', 'Вьетнам', 'VN / VNM', '84', 'vietnam.png', '../assets/img/flags/vietnam.png'),
	(608, 'Western Sahara', 'Западная Сахара', 'EH / ESH', '212', 'western_sahara.png', '../assets/img/flags/western_sahara.png'),
	(609, 'Yemen', 'Йемен', 'YE / YEM', '967', 'yemen.png', '../assets/img/flags/yemen.png'),
	(610, 'Zambia', 'Замбия', 'ZM / ZMB', '260', 'zambia.png', '../assets/img/flags/zambia.png'),
	(611, 'Zimbabwe', 'Зимбабве', 'ZW / ZWE', '263', 'zimbabwe.png', '../assets/img/flags/zimbabwe.png');
/*!40000 ALTER TABLE `countries_and_codes` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
